### PR TITLE
Propose talk by Cristian Klein

### PR DESCRIPTION
**Pull request by cristiklein**

### CODE REVIEW

**Review by gangsta — APPROVED** [review]
Thanks for PR Cristian,

And thanks for Contribution and Talk proposal :tada: :+1: 

All looks good.

**Comment by gangsta** [comment]
Next week we'll publish in all channels.

**Comment by cristiklein** [comment]
Thanks @gangsta !

Just to make sure, do I understand correctly that all I need to do is:

- show up at Foo Café, Carlsgatan 12 a, 211 20 Malmö at 17.00
- bring a laptop with HDMI output.

Will you organize the rest (e.g., booking venue, ordering pizza, what not)?

**Comment by gangsta** [comment]
> Thanks @gangsta !
> 
> Just to make sure, do I understand correctly that all I need to do is:
> 
>     * show up at Foo Café, Carlsgatan 12 a, 211 20 Malmö at 17.00
> 
>     * bring a laptop with HDMI output.
> 
> 
> Will you organize the rest (e.g., booking venue, ordering pizza, what not)?

Yes correct, All you need is that :)

The rest is Organized by the group and Foo Café.

**Comment by cristiklein** [comment]
Awesome, thanks!

**Pull request merged**
