### PR TITLE
adding talk about Jenkins X

### PR DESCRIPTION
**Pull request by hferentschik**
See issue #29

### CODE REVIEW

**Comment by gangsta** [comment]
Pull Request LGTM , I only see one missing part here,
Could you please add in Readme md as others did ? (Checkbox date talk speaker)
Later after presentation you can share slides using the same Readme , to link to presentation.
You can also checkout Guidelines of Meetups :+1: 
Sorry for inconvenience .

**Review by gangsta — CHANGES_REQUESTED** [review]
Readme.md missing line

**Comment by hferentschik** [comment]
@gangsta, updated the PR. Let me know if there is still something missing/wrong.

**Review by gangsta — APPROVED** [review]
LGTM

**Comment by gangsta** [comment]
Social Media Promotion planned to be Thursday|Friday , and week before Meetup date :+1: 
Great PR, looking forward to have it hosted :+1:

**Pull request merged**
