### PR TITLE
Request for talk

### PR DESCRIPTION
**Pull request by cypres**
I have an istio talk that has been fairly popular in the Cloud Native meetups, maybe it could be something for Devops Malmö?

### CODE REVIEW

**Comment by gangsta** [comment]
Talk Idea sounds to me good, and it's trending Topic.
please check our guidelines for presentation.
checkbox your talk
checkbox vanue FooCafe
and suggested date for me would be 27-28 January 2020 ?

**Comment by gangsta** [comment]
Date is not written is stone , if you have any other suggested date let me know , keep in mind there is big even FOSDEM 1-2 February , so lots of people probably will attend that one

**Comment by cypres** [comment]
I am flexible when it comes to dates, in the meetup groups I frequent we would have two talks per meetup. Do you usually do only a single talk in a meetup?

Was thinking I could piggy back on the Jan 14th meetup, or whenever you have a meetup again.

**Comment by gangsta** [comment]
yeah it has been proven that more people leave after pizza , and we don't want take all evening from members , and due to dark evenings we have decided to be secure its better to keep it shorter during winter time , maybe in mid June we could host meetup with 2 talks

**Comment by gangsta** [comment]
than lets go for Tuesday 28 January 2020 ?

**Comment by gangsta** [comment]
awesome , setting 24 hours timeout for @kvarak and @velith .
If no changes requested will merge to master .
Promotion will be 
1st around 20-23 December
2nd week before Meetup

Publishing around 18-19 December. :+1:

**Review by gangsta — APPROVED** [review]
LGTM :+1:

**Comment by cypres** [comment]
BTW The presentation includes a 2 minute or less recorded demo, because it demos work at a former employer so I don't have access to the systems involved anymore.

**Comment by gangsta** [comment]
that's fine no worries :+1:

**Pull request merged**
